name: build-package

on:
  pull_request:
    paths-ignore:
      - 'examples/**'
    branches:
      - main
          
jobs:
  build:
    name: build-package
    uses: newazmir/shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: build
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
