name: publish-package

on:
  push:
    paths-ignore:
      - 'examples/**'
    branches:
      - main

jobs:
  build:
    name: release-package
    uses: newazmir/shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: main
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
