name: publish-alpha-package

on:
  push:
    paths-ignore:
      - 'examples/**'
    branches:
      - 'alpha/**'

jobs:
  build:
    name: Publish Alpha Package
    uses: newazmir/shared-workflows/.github/workflows/net6-package.yml@main
    with:
      build: alpha
    secrets:
      GITHUB_PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      GITHUB_PACKAGE_USERNAME: ${{ secrets.PACKAGE_USERNAME }}
